DROP TABLE IF EXISTS money_owed;
DROP TABLE IF EXISTS people;
DROP TABLE IF EXISTS income;
DROP TABLE IF EXISTS expense;
DROP TABLE IF EXISTS budget;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS active_user;